  "swaggerDoc": {
    "openapi": "3.0.0",
    "info": {
      "version": "1",
      "title": "GitKraken Glo API",
      "description": "API for GitKraken Glo - access Glo boards and cards",
      "contact": {
        "name": "GitKraken Support",
        "url": "https://support.gitkraken.com/developers/overview/",
        "email": "support@gitkraken.com"
      }
    },
    "servers": [
      {
        "url": "https://gloapi.gitkraken.com/v1/glo",
        "description": "Glo API"
      }
    ],
    "components": {
      "securitySchemes": {
        "api_oauth": {
          "type": "oauth2",
          "description": "The Glo API uses OAuth 2",
          "bearerFormat": "Bearer",
          "flows": {
            "authorizationCode": {
              "authorizationUrl": "https://app.gitkraken.com/oauth/authorize",
              "tokenUrl": "https://api.gitkraken.com/oauth/access_token",
              "scopes": {
                "board:read": "Read boards",
                "board:write": "Write boards",
                "user:read": "Read user",
                "user:write": "Write user"
              }
            }
          }
        }
      }
    },
    "paths": {
      "/boards": {
        "get": {
          "summary": "Gets a list of boards",
          "description": "Note: `members` and `invited_members` in the results will not include the `username` field",
          "tags": [
            "Boards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}": {
        "get": {
          "summary": "Gets a board by ID",
          "tags": [
            "Boards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/columns": {
        "post": {
          "summary": "Creates a new column in a board",
          "tags": [
            "Columns"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/columns/{column_id}": {
        "post": {
          "summary": "Edits a column by ID",
          "tags": [
            "Columns"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        },
        "delete": {
          "summary": "Deletes a column by ID",
          "tags": [
            "Columns"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/cards": {
        "get": {
          "summary": "Gets a list of cards for a board",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        },
        "post": {
          "summary": "Creates a new card in a column",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/cards/{card_id}": {
        "get": {
          "summary": "Gets a card by ID",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        },
        "post": {
          "summary": "Edits a card",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        },
        "delete": {
          "summary": "Deletes a card",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/cards/{card_id}/attachments": {
        "get": {
          "summary": "Gets a list of attachments for a card",
          "tags": [
            "Attachments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        },
        "post": {
          "summary": "Creates an attachment for a card",
          "description": "**⚠️ Important Note:**\n\nAfter making this call, you must make another call to either update the card's description or add/update one of the card's comments and include the attachment url (in markdown format) in the text.\n\nThe format must be `[ANY_TEXT](ATTACHMENT_URL)`.\n\nIf the attachment url is not in the card description or one of its comments within 1 hour of the attachment being created, it will be deleted.\n",
          "tags": [
            "Attachments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/cards/{card_id}/comments": {
        "get": {
          "summary": "Gets a list of comments for a card",
          "tags": [
            "Comments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        },
        "post": {
          "summary": "Creates a new comment in a card",
          "tags": [
            "Comments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/cards/{card_id}/comments/{comment_id}": {
        "post": {
          "summary": "Edits a comment by ID",
          "tags": [
            "Comments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        },
        "delete": {
          "summary": "Deletes a comment by ID",
          "tags": [
            "Comments"
          ],
          "security": [
            {
              "api_oauth": [
                "board:write"
              ]
            }
          ]
        }
      },
      "/boards/{board_id}/columns/{column_id}/cards": {
        "get": {
          "summary": "Gets a list of cards for a column",
          "tags": [
            "Cards"
          ],
          "security": [
            {
              "api_oauth": [
                "board:read"
              ]
            }
          ]
        }
      },
      "/user": {
        "get": {
          "summary": "Gets data about the authenticated user",
          "tags": [
            "Users"
          ],
          "security": [
            {
              "api_oauth": [
                "user:read"
              ]
            }
          ]
        }
      }
    }
  },
  "customOptions": {
    "oauth2RedirectUrl": "https://gloapi.gitkraken.com/v1/docs/oauth2-redirect.html"
  }

